language: objective-c

osx_image: xcode8

env:
  -EARLY_START_SIMULATOR=1 # early starting simulator reduces false negatives due to test timeouts

before_install:
  - brew update
  - gem install cocoapods xcpretty --no-ri --no-rdoc
  - pod repo update --silent

after_failure:
    - sleep 10 # This prevents the occasional output truncation that happens when piping to xcpretty.

script: make

